version: '3.1'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 172.31.24.1:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /srv/nfs/wordpress:/var/www/html
