version: '3.1'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./ssl.conf:/etc/nginx/ssl.conf
    ports:
      - 80:80
      - 443:443
